# Generated by Django 4.2 on 2024-11-16 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KafkaConsumerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_topic', models.CharField(db_index=True, max_length=100)),
                ('event_key', models.CharField(blank=True, max_length=100, null=True)),
                ('event_value', models.TextField()),
                ('is_success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kafka Consumer Log',
                'verbose_name_plural': 'Kafka Consumer Logs',
            },
        ),
    ]
