# Generated by Django 4.2 on 2024-11-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(unique=True)),
                ('email', models.CharField(unique=True)),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
            ],
        ),
    ]
